version: '3.9'

services:

  app:
    build:
      context: ./src
    ports:
      - "8000:8000"
    restart: always
    image: translator:latest
    container_name: T5-BASE-API
    volumes:
      - .:/app:rw
